/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HPSSIXD_COMM_H_RPCGEN
#define _HPSSIXD_COMM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define HPSSIXD_SCANNER 0x49550001
#define SCANNER_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define scanner_connect 1
extern  int * scanner_connect_1(int *, CLIENT *);
extern  int * scanner_connect_1_svc(int *, struct svc_req *);
extern int hpssixd_scanner_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define scanner_connect 1
extern  int * scanner_connect_1();
extern  int * scanner_connect_1_svc();
extern int hpssixd_scanner_1_freeresult ();
#endif /* K&R C */

#define HPSSIXD_BUILDER 0x49550002
#define BUILDER_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define builder_run 1
extern  int * builder_run_1(u_quad_t *, CLIENT *);
extern  int * builder_run_1_svc(u_quad_t *, struct svc_req *);
#define builder_alive 2
extern  int * builder_alive_1(void *, CLIENT *);
extern  int * builder_alive_1_svc(void *, struct svc_req *);
#define builder_terminate 3
extern  int * builder_terminate_1(void *, CLIENT *);
extern  int * builder_terminate_1_svc(void *, struct svc_req *);
extern int hpssixd_builder_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define builder_run 1
extern  int * builder_run_1();
extern  int * builder_run_1_svc();
#define builder_alive 2
extern  int * builder_alive_1();
extern  int * builder_alive_1_svc();
#define builder_terminate 3
extern  int * builder_terminate_1();
extern  int * builder_terminate_1_svc();
extern int hpssixd_builder_1_freeresult ();
#endif /* K&R C */

#define HPSSIXD_EXTRACTOR 0x49550003
#define EXTRACTOR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define extractor_run 1
extern  int * extractor_run_1(u_quad_t *, CLIENT *);
extern  int * extractor_run_1_svc(u_quad_t *, struct svc_req *);
#define extractor_alive 2
extern  int * extractor_alive_1(void *, CLIENT *);
extern  int * extractor_alive_1_svc(void *, struct svc_req *);
#define extractor_terminate 3
extern  int * extractor_terminate_1(void *, CLIENT *);
extern  int * extractor_terminate_1_svc(void *, struct svc_req *);
extern int hpssixd_extractor_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define extractor_run 1
extern  int * extractor_run_1();
extern  int * extractor_run_1_svc();
#define extractor_alive 2
extern  int * extractor_alive_1();
extern  int * extractor_alive_1_svc();
#define extractor_terminate 3
extern  int * extractor_terminate_1();
extern  int * extractor_terminate_1_svc();
extern int hpssixd_extractor_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HPSSIXD_COMM_H_RPCGEN */
